package net.caramel.snare.gui;
import java.util.*; import net.caramel.snare.config.ConfigManager; import net.caramel.snare.module.Module; import net.caramel.snare.module.ModuleCategory; import net.caramel.snare.module.ModuleManager; import net.caramel.snare.setting.*; import net.caramel.snare.terminal.TerminalState;
import net.minecraft.client.gui.DrawContext; import net.minecraft.client.gui.screen.Screen; import net.minecraft.client.gui.widget.TextFieldWidget; import net.minecraft.client.util.InputUtil; import net.minecraft.text.Text; import org.lwjgl.glfw.GLFW;
public final class SnareScreen extends Screen {
 private enum Tab{COMMAND,MODULES} private static Tab sessionTab=Tab.MODULES;
 private static final int BG=0xF0101014,PANEL=0xFF181820,BORDER=0xFF34303E,TEXT=0xFFE9E5F0,MUTED=0xFF918B9C,ACCENT=0xFF9B6CFF,ROW=18;
 private final ModuleManager modules; private final TerminalState terminal; private final ConfigManager config; private final Set<ModuleCategory> expanded=new LinkedHashSet<>();
 private Module selected; private TextFieldWidget commandField; private final Map<TextSetting,TextFieldWidget> textFields=new LinkedHashMap<>(); private KeybindSetting capturing; private double sideScroll,settingsScroll,terminalScroll; private NumberSetting dragging;
 private int left,top,right,bottom,contentTop,sidebarRight;
 public SnareScreen(ModuleManager modules,TerminalState terminal,ConfigManager config){super(Text.literal("Snare"));this.modules=modules;this.terminal=terminal;this.config=config;modules.groupedByCategory().keySet().stream().findFirst().ifPresent(expanded::add);}
 @Override protected void init(){layout(); rebuildFields(); clampScrolls();}
 private void layout(){int w=Math.min(720,Math.max(300,width-24)),h=Math.min(440,Math.max(210,height-24));left=(width-w)/2;top=(height-h)/2;right=left+w;bottom=top+h;contentTop=top+34;sidebarRight=left+Math.max(105,Math.min(170,w/3));}
 private void rebuildFields(){if(commandField!=null)remove(commandField);commandField=null;textFields.values().forEach(this::remove);textFields.clear();if(sessionTab==Tab.COMMAND){commandField=new TextFieldWidget(textRenderer,left+10,bottom-26,right-left-20,18,Text.literal("Command"));commandField.setMaxLength(256);addDrawableChild(commandField);}else if(selected!=null){int y=contentTop+58-(int)settingsScroll;for(Setting<?> s:selected.settings())if(s.isVisible()){if(s instanceof TextSetting text){TextFieldWidget widget=new TextFieldWidget(textRenderer,sidebarRight+12,y+12,right-sidebarRight-24,18,Text.literal(text.name()));widget.setText(text.value());widget.setChangedListener(text::setValue);widget.setVisible(y+12>=contentTop&&y+30<=bottom);textFields.put(text,widget);addDrawableChild(widget);}y+=controlHeight(s);}}}
 private void clearFieldFocus(){if(commandField!=null)commandField.setFocused(false);textFields.values().forEach(widget->widget.setFocused(false));}
 private int controlHeight(Setting<?> s){return s instanceof TextSetting?42:34;}
 @Override public void render(DrawContext c,int mx,int my,float delta){c.fill(0,0,width,height,0xA0000000);c.fill(left,top,right,bottom,BG);c.drawBorder(left,top,right-left,bottom-top,BORDER);c.drawTextWithShadow(textRenderer,"SNARE",left+10,top+10,TEXT);tab(c,"Command",left+82,Tab.COMMAND,mx,my);tab(c,"Modules",left+148,Tab.MODULES,mx,my);c.fill(left,top+32,right,top+33,BORDER);if(sessionTab==Tab.COMMAND)renderCommand(c);else renderModules(c,mx,my);super.render(c,mx,my,delta);}
 private void tab(DrawContext c,String label,int x,Tab tab,int mx,int my){int color=sessionTab==tab?TEXT:MUTED;c.drawTextWithShadow(textRenderer,label,x,top+11,color);if(sessionTab==tab)c.fill(x,top+29,x+textRenderer.getWidth(label),top+32,ACCENT);}
 private void renderCommand(DrawContext c){int x1=left+10,y1=contentTop+8,x2=right-10,y2=bottom-32;c.fill(x1,y1,x2,y2,PANEL);c.enableScissor(x1,y1,x2,y2);int y=y2-12-(terminal.output().size()-1)*12+(int)terminalScroll;for(String line:terminal.output()){c.drawText(textRenderer,line,x1+6,y,line.startsWith(">")?TEXT:MUTED,false);y+=12;}c.disableScissor();}
 private void renderModules(DrawContext c,int mx,int my){c.fill(left+1,contentTop,sidebarRight,bottom-1,PANEL);c.fill(sidebarRight,contentTop,sidebarRight+1,bottom-1,BORDER);c.enableScissor(left+1,contentTop,sidebarRight,bottom-1);int y=contentTop+5-(int)sideScroll;for(var entry:modules.groupedByCategory().entrySet()){ModuleCategory category=entry.getKey();c.drawTextWithShadow(textRenderer,(expanded.contains(category)?"- ":"+ ")+category.name(),left+8,y+5,TEXT);y+=ROW;if(expanded.contains(category))for(Module module:entry.getValue()){if(module==selected)c.fill(left+5,y,sidebarRight-5,y+ROW,0xFF302541);c.drawText(textRenderer,module.name(),left+12,y+5,module==selected?0xFFFFFFFF:MUTED,false);c.fill(sidebarRight-24,y+5,sidebarRight-10,y+13,module.isEnabled()?ACCENT:BORDER);y+=ROW;}}c.disableScissor();renderSettings(c,mx,my);}
 private void renderSettings(DrawContext c,int mx,int my){int x=sidebarRight+12,y=contentTop+10-(int)settingsScroll;c.enableScissor(sidebarRight+1,contentTop,right-1,bottom-1);if(selected==null)c.drawTextWithShadow(textRenderer,"Select a module",x,y,MUTED);else{c.drawTextWithShadow(textRenderer,selected.name(),x,y,TEXT);c.drawText(textRenderer,selected.description(),x,y+14,MUTED,false);c.drawText(textRenderer,selected.isEnabled()?"Enabled":"Disabled",x,y+28,selected.isEnabled()?ACCENT:MUTED,false);y+=48;if(selected.settings().isEmpty())c.drawText(textRenderer,"No settings",x,y,MUTED,false);for(Setting<?> s:selected.settings())if(s.isVisible()){c.drawTextWithShadow(textRenderer,s.name(),x,y,TEXT);int controlY=y+12;if(s instanceof BooleanSetting b){c.fill(right-48,controlY,right-14,controlY+12,b.value()?ACCENT:BORDER);c.drawText(textRenderer,b.value()?"ON":"OFF",right-44,controlY+2,0xFFFFFFFF,false);}else if(s instanceof NumberSetting n){int sx=x,ex=right-14;c.fill(sx,controlY+5,ex,controlY+8,BORDER);c.fill(sx,controlY+5,sx+(int)((ex-sx)*n.ratio()),controlY+8,ACCENT);c.drawText(textRenderer,format(n.value()),x,controlY+11,MUTED,false);}else if(s instanceof ModeSetting m){c.drawText(textRenderer,"< "+m.value()+" >",right-14-textRenderer.getWidth("< "+m.value()+" >"),controlY,TEXT,false);}else if(s instanceof KeybindSetting k){String name=k.value()==KeybindSetting.UNBOUND?"Unbound":InputUtil.fromKeyCode(k.value(),0).getLocalizedText().getString();c.drawText(textRenderer,capturing==k?"Press a key":name,x,controlY,capturing==k?ACCENT:MUTED,false);c.drawText(textRenderer,"Clear",right-42,controlY,MUTED,false);}y+=controlHeight(s);}}c.disableScissor();}
 private static String format(double value){return value==Math.rint(value)?Long.toString(Math.round(value)):String.format(java.util.Locale.ROOT,"%.2f",value);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(button!=GLFW.GLFW_MOUSE_BUTTON_LEFT&&button!=GLFW.GLFW_MOUSE_BUTTON_RIGHT)return false;if(in(mx,my,left+82,top+6,left+137,top+30)){switchTab(Tab.COMMAND);return true;}if(in(mx,my,left+148,top+6,left+210,top+30)){switchTab(Tab.MODULES);return true;}if(sessionTab==Tab.COMMAND)return super.mouseClicked(mx,my,button);if(!in(mx,my,left,contentTop,right,bottom))return false;if(mx<sidebarRight){int y=contentTop+5-(int)sideScroll;for(var entry:modules.groupedByCategory().entrySet()){if(in(mx,my,left,y,sidebarRight,y+ROW)){if(!expanded.remove(entry.getKey()))expanded.add(entry.getKey());clampScrolls();return true;}y+=ROW;if(expanded.contains(entry.getKey()))for(Module module:entry.getValue()){if(in(mx,my,left,y,sidebarRight,y+ROW)){if(mx>=sidebarRight-32)module.toggle();else{selected=module;capturing=null;settingsScroll=0;rebuildFields();}return true;}y+=ROW;}}return false;}return clickSetting(mx,my,button);}
 private boolean clickSetting(double mx,double my,int button){if(selected==null)return false;int x=sidebarRight+12,y=contentTop+58-(int)settingsScroll;for(Setting<?> s:selected.settings())if(s.isVisible()){if(in(mx,my,x,y,right-10,y+controlHeight(s))){if(s instanceof TextSetting)return super.mouseClicked(mx,my,button);clearFieldFocus();if(s instanceof BooleanSetting b)b.setValue(!b.value());else if(s instanceof NumberSetting n){dragging=n;setSlider(n,mx,x,right-14);}else if(s instanceof ModeSetting m)m.cycle(button==GLFW.GLFW_MOUSE_BUTTON_RIGHT?-1:1);else if(s instanceof KeybindSetting k){if(mx>=right-50)k.setValue(KeybindSetting.UNBOUND);else capturing=k;}return true;}y+=controlHeight(s);}return super.mouseClicked(mx,my,button);}
 @Override public boolean mouseDragged(double mx,double my,int button,double dx,double dy){if(dragging!=null){setSlider(dragging,mx,sidebarRight+12,right-14);return true;}return super.mouseDragged(mx,my,button,dx,dy);}
 @Override public boolean mouseReleased(double mx,double my,int button){dragging=null;return super.mouseReleased(mx,my,button);}
 private static void setSlider(NumberSetting n,double mx,int start,int end){n.setRatio((mx-start)/(end-start));}
 @Override public boolean mouseScrolled(double mx,double my,double amount){double delta=-amount*18;if(sessionTab==Tab.COMMAND)terminalScroll+=delta;else if(mx<sidebarRight)sideScroll+=delta;else settingsScroll+=delta;clampScrolls();rebuildFields();return true;}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if(capturing!=null){if(key==GLFW.GLFW_KEY_ESCAPE){capturing=null;return true;}capturing.setValue(key);capturing=null;return true;}if(sessionTab==Tab.COMMAND&&commandField!=null){if(key==GLFW.GLFW_KEY_ENTER&&terminal.submit(commandField.getText())){commandField.setText("");terminalScroll=0;return true;}if(key==GLFW.GLFW_KEY_UP){commandField.setText(terminal.historyUp(commandField.getText()));commandField.setCursorToEnd();return true;}if(key==GLFW.GLFW_KEY_DOWN){commandField.setText(terminal.historyDown());commandField.setCursorToEnd();return true;}}return super.keyPressed(key,scan,modifiers);}
 private void switchTab(Tab tab){if(sessionTab==tab)return;sessionTab=tab;capturing=null;dragging=null;clearFieldFocus();rebuildFields();}
 private void clampScrolls(){int sideHeight=5+modules.groupedByCategory().entrySet().stream().mapToInt(e->ROW+(expanded.contains(e.getKey())?e.getValue().size()*ROW:0)).sum();sideScroll=clamp(sideScroll,0,Math.max(0,sideHeight-(bottom-contentTop)));int settingHeight=selected==null?0:58+selected.settings().stream().filter(Setting::isVisible).mapToInt(this::controlHeight).sum();settingsScroll=clamp(settingsScroll,0,Math.max(0,settingHeight-(bottom-contentTop)));int terminalHeight=terminal.output().size()*12;terminalScroll=clamp(terminalScroll,0,Math.max(0,terminalHeight-(bottom-contentTop-42)));}
 private static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}private static boolean in(double x,double y,int x1,int y1,int x2,int y2){return x>=x1&&x<x2&&y>=y1&&y<y2;}
 @Override public void resize(net.minecraft.client.MinecraftClient client,int width,int height){super.resize(client,width,height);layout();clampScrolls();rebuildFields();}
 @Override public void close(){capturing=null;dragging=null;clearFieldFocus();config.flush();super.close();}
 @Override public boolean shouldPause(){return true;}
}